name: Build pandas
description: Rebuilds the C extensions and installs pandas
inputs:
  editable:
    description: Whether to build in editable mode
    default: "true"
  werror:
    description: Enable werror flag
    default: "true"
runs:
  using: composite
  steps:
    - name: Build Pandas
      run: |
        if [[ ${{ inputs.editable }} == "true" ]]; then
          echo "editable mode: pip install -e ."
        else
          echo "non-editable mode: pip install ."
        fi
      shell: bash -el {0}
